import { Website } from "./WebsiteHighlights";
export const websitesData: Website[] = [
  {
    id: crypto.randomUUID(),
    url: "https://react.dev",
    highlights: [
      {
        id: crypto.randomUUID(),
        title: "Hooks are powerful",
        description: "Manage component state with clean, reusable logic.",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Declarative UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Last UI",
        description: "Describe how UI should look — React handles the updates.",
        color: "bg-green-100 border-green-300",
      },
    ],
  },
  {
    id: crypto.randomUUID(),
    url: "https://tailwindcss.com",
    highlights: [
      {
        id: crypto.randomUUID(),
        title: "Utility-first design",
        description: "Compose interfaces quickly with small, reusable classes.",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Responsive by default",
        description: "Easily design for any screen size.",
        color: "bg-purple-100 border-purple-300",
      },
    ],
  },
  {
    id: crypto.randomUUID(),
    url: "https://nextjs.org",
    highlights: [
      {
        id: crypto.randomUUID(),
        title: "Server components",
        description: "Render faster and ship less JS to the client.",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: crypto.randomUUID(),
        title: "Built-in routing",
        description: "Optimized routes, layouts, and APIs with zero setup.",
        color: "bg-orange-100 border-orange-300",
      },
    ],
  },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },

  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://nextjs.org", highlights: [] },
  { id: crypto.randomUUID(), url: "https://last.org", highlights: [] },
];
